spring.application.name=ms-envios
server.port=8084

# MySQL Aiven
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# RabbitMQ CloudAMQP
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

# Colas y exchange
rabbitmq.queue.envio=envio.generar
rabbitmq.exchange=pedidos.exchange

# MailerSend
mailersend.api-key=${MAILERSEND_API_KEY}
mailersend.from-email=${MAILERSEND_FROM_EMAIL}
mailersend.from-name=Syncro